print('Hey sexy...')
print('Whats yo name???')
myName = input()
print('It is good to meet you, '+myName+', with yo sexy ass')
print('The length of your name is:')
print(len(myName))
print('How old are you???')
myAge = input()
print('You look good for '+myAge+', and to think you will be '+str(int(myAge)+1)+' in a year.')